[package]
name = "common-tree"
version = "0.2.0"
authors = ["chen <chanble_cn@163.com>"]
edition = "2018"
description = "common tree lib"
repository = "https://github.com/chanble/common-tree"
homepage = "https://github.com/chanble/common-tree"
readme = "README.md"
license="MIT"

[dependencies]
